version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -o terraform.zip -L https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -o terraform.zip && mv terraform /usr/local/bin/
  build:
    commands:
      - cp $CODEBUILD_SRC_DIR_build_output/services/ingest-sharepoint-lambda/infra/tfplan services/ingest-sharepoint-lambda/infra/tfplan
      - mkdir -p modules/lambda-function/.build
      - cp $CODEBUILD_SRC_DIR_build_output/modules/lambda-function/.build/lambda-ingest-sharepoint-${ENVIRONMENT}.zip modules/lambda-function/.build/lambda-ingest-sharepoint-${ENVIRONMENT}.zip
      - cd services/ingest-sharepoint-lambda/infra
      - terraform init
          -backend-config="bucket=${TFSTATE_BUCKET}"
          -backend-config="key=services/ingest-sharepoint-lambda/${ENVIRONMENT}/terraform.tfstate"
          -backend-config="region=${TFSTATE_REGION}"
      - terraform apply -auto-approve tfplan
