version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -o terraform.zip -L https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -o terraform.zip && mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Aplicando fuente: ${FUENTE}"
      - cp $CODEBUILD_SRC_DIR_build_output/multi-fuente-demo/fuentes/fuente-${FUENTE}/infra/tfplan multi-fuente-demo/fuentes/fuente-${FUENTE}/infra/tfplan
      - |
        if [ "${FUENTE}" = "sqlserver" ]; then
          mkdir -p multi-fuente-demo/modules/lambda-function/.build
          cp $CODEBUILD_SRC_DIR_build_output/multi-fuente-demo/modules/lambda-function/.build/multi-fuente-sqlserver-audit-${ENVIRONMENT}.zip multi-fuente-demo/modules/lambda-function/.build/multi-fuente-sqlserver-audit-${ENVIRONMENT}.zip
        fi
      - cd multi-fuente-demo/fuentes/fuente-${FUENTE}/infra
      - terraform init
          -backend-config="bucket=${TFSTATE_BUCKET}"
          -backend-config="key=multi-fuente-demo/fuentes/fuente-${FUENTE}/${ENVIRONMENT}/terraform.tfstate"
          -backend-config="region=${TFSTATE_REGION}"
      - terraform apply -auto-approve tfplan
