version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -o terraform.zip -L https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -o terraform.zip && mv terraform /usr/local/bin/
  build:
    commands:
      - cd services/clean-service/infra
      - terraform init
          -backend-config="bucket=${TFSTATE_BUCKET}"
          -backend-config="key=services/clean-service/${ENVIRONMENT}/terraform.tfstate"
          -backend-config="region=${TFSTATE_REGION}"
      - terraform plan
          -var-file="../../../env/${ENVIRONMENT}.tfvars"
          -var="region=${AWS_DEFAULT_REGION}"
          -out=tfplan

artifacts:
  files:
    - services/clean-service/infra/*.tf
    - services/clean-service/infra/tfplan
    - services/clean-service/buildspec-apply.yml
