environment           = "dev"
region                = "us-east-1"
project_name          = "data-platform"

platform_state_bucket = "CAMBIA-ESTE-BUCKET-tfstate"
platform_state_region = "us-east-1"
branch = "dev"
repo_connection_arn   = "arn:aws:codestar-connections:us-east-1:123456789012:connection/CAMBIA-ESTE-ID"
repo_full_name        = "tu-org/data-platform"
artifact_bucket       = "CAMBIA-ESTE-BUCKET-artifacts-dev"
