environment           = "prod"
region                = "us-west-2"
project_name          = "data-platform"

platform_state_bucket = "CAMBIA-ESTE-BUCKET-tfstate"
platform_state_region = "us-east-1"
branch = "main"
repo_connection_arn   = "arn:aws:codestar-connections:us-west-2:123456789012:connection/CAMBIA-ESTE-ID"
repo_full_name        = "tu-org/data-platform"
artifact_bucket       = "CAMBIA-ESTE-BUCKET-artifacts-prod"
